# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 17:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='nickname_color',
            new_name='color',
        ),
    ]
