# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 18:16
from __future__ import unicode_literals

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20170128_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='profile',
            name='color',
            field=colorful.fields.RGBColorField(colors=['#FF0000', '#00FF00', '#0000FF'], default='#000'),
        ),
    ]
