# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 18:17
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20170128_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='color2',
            field=colorfield.fields.ColorField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
