# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 23:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20170128_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='main_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_category', to='post.Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='secondary_categories',
            field=models.ManyToManyField(blank=True, related_name='secondary_categories', to='post.Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='post.Tag'),
        ),
    ]
