# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 15:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20170128_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='desctiption',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='desctiption',
            new_name='description',
        ),
    ]
