# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20170128_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='archived',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='category',
            name='archived_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='archived',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='tag',
            name='archived_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
