# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_auto_20170128_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='archived',
        ),
        migrations.RemoveField(
            model_name='category',
            name='archived_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='main_category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='secondary_categories',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='archived',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='archived_at',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='post.Category'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='archived_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='archived_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
