# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170219_1228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'ordering': ('is_current',), 'verbose_name_plural': 'About'},
        ),
        migrations.AlterModelOptions(
            name='social',
            options={'verbose_name_plural': 'Social'},
        ),
        migrations.AddField(
            model_name='social',
            name='ordering',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='social',
            name='font_awesome_icon_tag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
