# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170219_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='ordering',
            field=models.IntegerField(unique=True),
        ),
    ]
