# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 13:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170219_1300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='social',
            options={'ordering': ('ordering',), 'verbose_name_plural': 'Social'},
        ),
        migrations.RenameField(
            model_name='social',
            old_name='title',
            new_name='name',
        ),
    ]
