# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_remove_post_publication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publication_status',
            field=models.CharField(choices=[('d', 'draft'), ('p', 'published')], default='d', max_length=1),
        ),
    ]
